config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations'}
  get 'home', :to => 'home#search'
  resources :registers
  root to: "students#index"
  resources :students
  resources :institutions
end
  
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/institution.rb
class Institution < ApplicationRecord
  has_many :students

  def self.search(name)
    Institution.where('name like :value', value: "%#{name}%").sort_by { |i| i.name }
  end
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :institution

  def self.search(name)
    Student.where('name like :value', value: "%#{name}%").sort_by { |s| s.name }
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def search
    students = Student.search(params[:name])
    institutions = Institution.search(params[:name])
    @results = students + institutions 
  end
end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_institution, only: [:show, :edit, :update, :destroy]

  # GET /institutions
  # GET /institutions.json
  def index
    @institutions = Institution.all
  end

  # GET /institutions/1
  # GET /institutions/1.json
  def show
  end

  # GET /institutions/new
  def new
    @institution = Institution.new
  end

  # GET /institutions/1/edit
  def edit
  end

  # POST /institutions
  # POST /institutions.json
  def create
    @institution = Institution.new(institution_params)

    respond_to do |format|
      if @institution.save
        format.html { redirect_to @institution, notice: 'Institution was successfully created.' }
        format.json { render :show, status: :created, location: @institution }
      else
        format.html { render :new }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /institutions/1
  # PATCH/PUT /institutions/1.json
  def update
    respond_to do |format|
      if @institution.update(institution_params)
        format.html { redirect_to @institution, notice: 'Institution was successfully updated.' }
        format.json { render :show, status: :ok, location: @institution }
      else
        format.html { render :edit }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /institutions/1
  # DELETE /institutions/1.json
  def destroy
    @institution.destroy
    respond_to do |format|
      format.html { redirect_to institutions_url, notice: 'Institution was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_institution
      @institution = Institution.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def institution_params
      params.require(:institution).permit(:name, :address, :phone)
    end
end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController
  before_action :set_student, only: [:destroy]
  
  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private
   def sign_up_params
    params.require(:user).permit(:phone, :email, :password, :password_confirmation)
  end 
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_user!, except: [:create]
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  STUDENT_PER_PAGE = 3
 
  def index
   @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_path(@student), notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    def sort_column
      Student.column_names.include?(params[:sort] ? params[:sort] : "full_name")
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :address, :mobile, :institution_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/helpers/registers_helper.rb
module RegistersHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/home/search.html.erb
<p id="notice"><%= notice %></p>
<h1>Students</h1>

<table class='table'>
<tbody>
    <% @results.each do |item| %>
      <tr>
      	<td>Name:<%= item.name %></td>
      	<td>Address:<%= item.address %></td>
      	<td>Name:<%= item.name %></td>
      	<td>Address:<%= item.address %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/institutions/_form.html.erb
<%= form_with(model: institution, local: true) do |form| %>
  <% if institution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(institution.errors.count, "error") %> prohibited this institution from being saved:</h2>

      <ul>
      <% institution.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_area :address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :phone %>
    <%= form.text_field :phone, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/institutions/edit.html.erb
<h1>Editing Institution</h1>

<%= render 'form', institution: @institution %>

<%= link_to 'Show', @institution %> |
<%= link_to 'Back', institutions_path %>

app/views/institutions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Institutions</h1>

<table class='table'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @institutions.each do |institution| %>
      <tr>
        <td><%= institution.name %></td>
        <td><%= institution.address %></td>
        <td><%= institution.phone %></td>
        <td><%= link_to 'Show', institution %></td>
        <td><%= link_to 'Edit', edit_institution_path(institution) %></td>
        <td><%= link_to 'Destroy', institution, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Institution', new_institution_path %>

app/views/institutions/new.html.erb
<h1>New Institution</h1>

<%= render 'form', institution: @institution %>

<%= link_to 'Back', institutions_path %>

app/views/institutions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @institution.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @institution.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @institution.phone %>
</p>

<%= link_to 'Edit', edit_institution_path(@institution) %> |
<%= link_to 'Back', institutions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentsDb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid bg-primary">
      <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="#">Student DB</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <%= link_to "Home", root_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "Add Student", new_student_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "Add Institution", new_institution_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "Register", registers_path, class: 'nav-link' %>
            </li>
             <%=render "/shared/header"%>
            </ul>
        </div>
      </nav>    
    </div>
    <div class="container">
      <%= yield %>
    </div>
    <%=render "/shared/footer"%>
  </body>
</html>

app/views/registers/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_area :address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :mobile %>
    <%= form.text_field :mobile, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :institution_id %>
    <%= form.select :institution_id, options_from_collection_for_select(Institution.all, :id, :name), {},class: "form-control form-control-lg" %>
  </div>


  <div class="actions">
    <%= form.submit 'Save' , class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/registers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table class='table'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.address %></td>
        <td><%= student.mobile %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
     </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_register_path %>

app/views/registers/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

app/views/shared/_footer.html.erb
<div class="footList">
<label class="copyLbl"> &copy; copyright 2020 Foradian </label>
</div>

app/views/shared/_header.html.erb
</li class="nav-item">
    <%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'nav-link'%>
</li>

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_area :address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :mobile %>
    <%= form.text_field :mobile, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :institution_id %>
    <%= form.select :institution_id, options_from_collection_for_select(Institution.all, :id, :name), {}, class: "form-control form-control-lg" %>
  </div>

  <div class="actions">
    <%= form.submit 'Save' , class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/students/_search_form.html.erb
<%= form_tag(home_path, :method => "get",   
    class: 'navbar-form navbar-left') do %>  
  <div class="input-group">  
    <%= search_field_tag :fullname, params[:name], placeholder: "Student Name", class: "form-control" %>  
    <%= search_field_tag :name, params[:name], placeholder: "Institution Name", class: "form-control" %>  
  <div class="input-group-btn">  
      <%= button_tag "", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>  
    </div>  
  </div>  
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<%= render "search_form" %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %><br>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @student.address %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @student.mobile %>
</p>

<p>
  <strong>Institution:</strong>
  <%= @student.institution.try(:name) %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>